version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    parallelism: 2

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn -pl maxur-mserv-core dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn verify -Denv=dev -Pdebug,dep-jacoco,kotlin

      - store_test_results:
          path: maxur-mserv-core/target/surefire-reports

      - run: bash <(curl -s https://codecov.io/bash)

  check:
    steps:

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn -pl maxur-mserv-core dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

    - run: mvn enforcer:enforce -P check-dep -pl maxur-mserv-core

workflows:
  version: 2
  build_and_test:
    jobs:
      - check
      - build
